// ================================================================
// RDM Digital OS v3 — Twin Context Builder
// Builds TwinContext array from in-memory places + merchants store
// This is the bridge between raw data and the GA/Realito systems
// ================================================================

import type { TwinContext } from "./types.js";

// ================================================================
// Canonical territorial data — Real del Monte verified locations
// Each entry represents a physical entity with its digital twin
// ================================================================

const PLACES_TWIN_DATA: TwinContext[] = [
  {
    id: "twin-centro-historico",
    modelType: "PLACE_TWIN",
    sourceId: "centro-historico",
    name: "Centro Histórico y Plaza Principal",
    lat: 20.1407,
    lng: -98.6725,
    tags: ["HISTORIA", "ARQUITECTURA", "CENTRO", "COLONIAL"],
    immersionLevel: 0.7,
    popularityScore: 0.9,
    telemetry: { crowdLevel: 0.45, weather: "cloudy", openStatus: true, flowIndex: 0.5, avgStayMinutes: 40, queueMinutes: 0 },
    properties: { type: "HISTORIC", immersion: "L2", narrative: "Corazón de Real del Monte con portales coloniales del siglo XVIII y memoria minera viva." },
  },
  {
    id: "twin-mina-acosta",
    modelType: "PLACE_TWIN",
    sourceId: "mina-de-acosta",
    name: "Mina de Acosta",
    lat: 20.1448,
    lng: -98.6653,
    tags: ["HISTORIA", "MUSEO", "MINA", "PATRIMONIO"],
    immersionLevel: 0.9,
    popularityScore: 0.95,
    telemetry: { crowdLevel: 0.3, weather: "cloudy", openStatus: true, flowIndex: 0.4, avgStayMinutes: 60, queueMinutes: 10 },
    properties: { type: "MUSEUM", immersion: "L3", narrative: "Mina histórica convertida en museo. Desciende 400m bajo tierra en túneles originales del siglo XIX." },
  },
  {
    id: "twin-panteon-ingles",
    modelType: "PLACE_TWIN",
    sourceId: "panteon-ingles",
    name: "Panteón Inglés",
    lat: 20.1397,
    lng: -98.6769,
    tags: ["HISTORIA", "PATRIMONIO", "BRITANICO"],
    immersionLevel: 0.8,
    popularityScore: 0.85,
    telemetry: { crowdLevel: 0.15, weather: "cloudy", openStatus: true, flowIndex: 0.2, avgStayMinutes: 30, queueMinutes: 0 },
    properties: { type: "HISTORIC", immersion: "L2", narrative: "Único cementerio inglés en Latinoamérica. Tumbas orientadas hacia Inglaterra." },
  },
  {
    id: "twin-parroquia-asuncion",
    modelType: "PLACE_TWIN",
    sourceId: "parroquia-asuncion",
    name: "Parroquia de la Asunción",
    lat: 20.1412,
    lng: -98.6738,
    tags: ["RELIGION", "ARQUITECTURA", "COLONIAL"],
    immersionLevel: 0.5,
    popularityScore: 0.6,
    telemetry: { crowdLevel: 0.2, weather: "cloudy", openStatus: true, flowIndex: 0.3, avgStayMinutes: 20, queueMinutes: 0 },
    properties: { type: "RELIGIOUS", immersion: "L1", narrative: "Iglesia colonial del siglo XVIII con retablos barrocos dorados." },
  },
  {
    id: "twin-museo-medicina",
    modelType: "PLACE_TWIN",
    sourceId: "museo-medicina",
    name: "Museo de Medicina Laboral",
    lat: 20.1405,
    lng: -98.6729,
    tags: ["MUSEO", "HISTORIA", "MEDICINA"],
    immersionLevel: 0.6,
    popularityScore: 0.5,
    telemetry: { crowdLevel: 0.1, weather: "cloudy", openStatus: true, flowIndex: 0.15, avgStayMinutes: 25, queueMinutes: 0 },
    properties: { type: "MUSEUM", immersion: "L1", narrative: "Documenta condiciones de salud de los mineros con instrumental del siglo XIX." },
  },
  {
    id: "twin-cristo-rey",
    modelType: "PLACE_TWIN",
    sourceId: "cristo-rey",
    name: "Cristo Rey (Peña del Zumate)",
    lat: 20.1460,
    lng: -98.6690,
    tags: ["MIRADOR", "NATURALEZA", "PANORAMICA", "AVENTURA"],
    immersionLevel: 0.7,
    popularityScore: 0.8,
    telemetry: { crowdLevel: 0.25, weather: "clear", openStatus: true, flowIndex: 0.3, avgStayMinutes: 35, queueMinutes: 0 },
    properties: { type: "VIEWPOINT", immersion: "L2", narrative: "Vistas panorámicas de 360° del pueblo y las montañas. Monumento icónico." },
  },
  {
    id: "twin-mina-dolores",
    modelType: "PLACE_TWIN",
    sourceId: "mina-dolores",
    name: "Mina de Dolores",
    lat: 20.1430,
    lng: -98.6700,
    tags: ["HISTORIA", "MINA", "PATRIMONIO"],
    immersionLevel: 0.5,
    popularityScore: 0.4,
    telemetry: { crowdLevel: 0.05, weather: "cloudy", openStatus: true, flowIndex: 0.1, avgStayMinutes: 20, queueMinutes: 0 },
    properties: { type: "MINE", immersion: "L1", narrative: "Una de las minas más profundas de la región, clave en la historia de la plata novohispana." },
  },
  {
    id: "twin-bosque-pinos",
    modelType: "PLACE_TWIN",
    sourceId: "bosque-pinos",
    name: "Bosque de Pinos y Oyameles",
    lat: 20.1556,
    lng: -98.6856,
    tags: ["NATURALEZA", "ECOTURISMO", "SENDERISMO", "AVENTURA"],
    immersionLevel: 0.6,
    popularityScore: 0.65,
    telemetry: { crowdLevel: 0.08, weather: "clear", openStatus: true, flowIndex: 0.12, avgStayMinutes: 90, queueMinutes: 0 },
    properties: { type: "NATURE", immersion: "L1", narrative: "Senderismo a 2,700m de altitud. Bosque de oyamel con aire puro de montaña." },
  },
  {
    id: "twin-mirador-atardecer",
    modelType: "PLACE_TWIN",
    sourceId: "mirador-atardecer",
    name: "Mirador del Atardecer",
    lat: 20.1489,
    lng: -98.6711,
    tags: ["MIRADOR", "NATURALEZA", "FOTOGRAFIA"],
    immersionLevel: 0.5,
    popularityScore: 0.55,
    telemetry: { crowdLevel: 0.12, weather: "clear", openStatus: true, flowIndex: 0.18, avgStayMinutes: 25, queueMinutes: 0 },
    properties: { type: "VIEWPOINT", immersion: "L1", narrative: "El mejor lugar para ver el atardecer sobre la sierra hidalguense." },
  },
  {
    id: "twin-vista-penon",
    modelType: "PLACE_TWIN",
    sourceId: "vista-penon",
    name: "Vista del Peñón",
    lat: 20.1511,
    lng: -98.6694,
    tags: ["MIRADOR", "NATURALEZA", "PANORAMICA"],
    immersionLevel: 0.4,
    popularityScore: 0.45,
    telemetry: { crowdLevel: 0.05, weather: "clear", openStatus: true, flowIndex: 0.08, avgStayMinutes: 20, queueMinutes: 0 },
    properties: { type: "VIEWPOINT", immersion: "L1", narrative: "Panorámica espectacular desde lo alto, con vistas al Valle del Mezquital." },
  },
];

const MERCHANTS_TWIN_DATA: TwinContext[] = [
  {
    id: "twin-pasteria-portal",
    modelType: "MERCHANT_TWIN",
    sourceId: "pasteria-el-portal",
    name: "Pastería El Portal",
    lat: 20.1409,
    lng: -98.6723,
    tags: ["GASTRONOMIA", "PASTES", "TRADICIONAL"],
    immersionLevel: 0.7,
    popularityScore: 0.9,
    telemetry: { crowdLevel: 0.6, openStatus: true, flowIndex: 0.55, avgStayMinutes: 30 },
    properties: { type: "FOOD", immersion: "L2", category: "FOOD", narrative: "Pastes tradicionales con receta córnica de 1824 frente a la plaza principal." },
  },
  {
    id: "twin-mina-coffee",
    modelType: "MERCHANT_TWIN",
    sourceId: "mina-coffee",
    name: "Mina Coffee House",
    lat: 20.1391,
    lng: -98.6752,
    tags: ["GASTRONOMIA", "CAFE", "ARTESANAL"],
    immersionLevel: 0.6,
    popularityScore: 0.7,
    telemetry: { crowdLevel: 0.4, openStatus: true, flowIndex: 0.35, avgStayMinutes: 40 },
    properties: { type: "FOOD", immersion: "L2", category: "FOOD", narrative: "Café artesanal y repostería en ambiente colonial." },
  },
  {
    id: "twin-hotel-real",
    modelType: "MERCHANT_TWIN",
    sourceId: "hotel-real",
    name: "Hotel Real del Monte",
    lat: 20.1456,
    lng: -98.6800,
    tags: ["HOSPEDAJE", "BOUTIQUE", "PANORAMICA"],
    immersionLevel: 0.8,
    popularityScore: 0.75,
    telemetry: { crowdLevel: 0.3, openStatus: true, flowIndex: 0.25 },
    properties: { type: "LODGING", immersion: "L3", category: "LODGING", narrative: "Hotel boutique con vista panorámica y chimenea en cada habitación." },
  },
  {
    id: "twin-artesanias-rdm",
    modelType: "MERCHANT_TWIN",
    sourceId: "artesanias-rdm",
    name: "Artesanías RDM",
    lat: 20.1385,
    lng: -98.6755,
    tags: ["ARTESANIAS", "CULTURA", "OBSIDIANA"],
    immersionLevel: 0.4,
    popularityScore: 0.5,
    telemetry: { crowdLevel: 0.2, openStatus: true, flowIndex: 0.15 },
    properties: { type: "HANDCRAFTS", immersion: "L1", category: "HANDCRAFTS", narrative: "Artesanías locales: cerámica, obsidiana, tapetes." },
  },
  {
    id: "twin-casa-tacos",
    modelType: "MERCHANT_TWIN",
    sourceId: "casa-tacos",
    name: "La Casa de los Tacos",
    lat: 20.1388,
    lng: -98.6748,
    tags: ["GASTRONOMIA", "TACOS", "ECONOMICO"],
    immersionLevel: 0.3,
    popularityScore: 0.65,
    telemetry: { crowdLevel: 0.5, openStatus: true, flowIndex: 0.4 },
    properties: { type: "FOOD", immersion: "L1", category: "FOOD", narrative: "Tacos de carnitas, barbacoa y lengua. Sabor auténtico de Hidalgo." },
  },
  {
    id: "twin-eco-aventuras",
    modelType: "MERCHANT_TWIN",
    sourceId: "eco-aventuras",
    name: "Eco Aventuras RDM",
    lat: 20.1500,
    lng: -98.6820,
    tags: ["ECOTURISMO", "AVENTURA", "RAPPEL"],
    immersionLevel: 0.9,
    popularityScore: 0.7,
    telemetry: { crowdLevel: 0.15, openStatus: true, flowIndex: 0.12 },
    properties: { type: "ACTIVITY", immersion: "L3", category: "ACTIVITY", narrative: "Tours de ecoturismo, rappelling y senderismo guiado." },
  },
  {
    id: "twin-bar-portal",
    modelType: "MERCHANT_TWIN",
    sourceId: "bar-portal",
    name: "Bar El Portal",
    lat: 20.1382,
    lng: -98.6753,
    tags: ["BAR", "MUSICA", "MEZCAL"],
    immersionLevel: 0.3,
    popularityScore: 0.55,
    telemetry: { crowdLevel: 0.35, openStatus: true, flowIndex: 0.3 },
    properties: { type: "BAR", immersion: "L1", category: "BAR", narrative: "Bar con música en vivo, mezcal artesanal y cerveza de montaña." },
  },
  {
    id: "twin-los-portales",
    modelType: "MERCHANT_TWIN",
    sourceId: "los-portales",
    name: "Restaurante Los Portales",
    lat: 20.1384,
    lng: -98.6758,
    tags: ["GASTRONOMIA", "MOLE", "COLONIAL"],
    immersionLevel: 0.6,
    popularityScore: 0.8,
    telemetry: { crowdLevel: 0.55, openStatus: true, flowIndex: 0.45 },
    properties: { type: "FOOD", immersion: "L2", category: "FOOD", narrative: "Comida típica hidalguense en ambiente colonial. Mole, barbacoa." },
  },
  {
    id: "twin-tours-historicos",
    modelType: "MERCHANT_TWIN",
    sourceId: "tours-historicos",
    name: "Tours Históricos RDM",
    lat: 20.1392,
    lng: -98.6754,
    tags: ["TOURS", "HISTORIA", "TEATRO"],
    immersionLevel: 0.7,
    popularityScore: 0.6,
    telemetry: { crowdLevel: 0.2, openStatus: true, flowIndex: 0.15 },
    properties: { type: "ACTIVITY", immersion: "L2", category: "ACTIVITY", narrative: "Recorridos guiados con actores caracterizados de época." },
  },
  {
    id: "twin-galeria-arte",
    modelType: "MERCHANT_TWIN",
    sourceId: "galeria-arte",
    name: "Galería de Arte Local",
    lat: 20.1390,
    lng: -98.6746,
    tags: ["ARTE", "CULTURA", "GALERIA"],
    immersionLevel: 0.4,
    popularityScore: 0.4,
    telemetry: { crowdLevel: 0.1, openStatus: true, flowIndex: 0.08 },
    properties: { type: "CULTURE", immersion: "L1", category: "CULTURE", narrative: "Exhibición y venta de arte local, pintura y fotografía." },
  },
];

export function buildTwinsContext(): TwinContext[] {
  return [...PLACES_TWIN_DATA, ...MERCHANTS_TWIN_DATA];
}

export function getTwinById(id: string): TwinContext | undefined {
  return buildTwinsContext().find((t) => t.id === id || t.sourceId === id);
}

export function getTwinsByType(type: string): TwinContext[] {
  return buildTwinsContext().filter((t) => {
    const twinType = ((t.properties.type as string) ?? "").toUpperCase();
    return twinType === type.toUpperCase() || t.modelType === type;
  });
}
