import { Router } from "express";
import authRouter from "./auth.js";
import businessesRouter from "./businesses.js";
import donationsRouter from "./donations.js";
import weatherRouter from "./weather.js";
import recommendationsRouter from "./recommendations.js";
import aiRouter from "./ai.js";
import digitalTwinsRouter from "./digital-twins.js";
import contentRouter from "./content.js";
import realitoRouter from "./realito.js";
import auditRouter from "./audit.js";
import xrRouter from "./xr.js";
import economyRouter from "./economy.js";
import protocolsRouter from "./protocols.js";
import streamsRouter from "./streams.js";
import socialRouter from "./social.js";
import profilesRouter from "./profiles.js";
import usersRouter from "./users.js";
import placesRouter from "./places.js";
import merchantsRouter from "./merchants.js";
import twinsRouter from "./twins.js";
import experienceRouter from "./experience.js";
import systemRouter from "./system.js";
import rdmxStatusRouter from "./rdmx-status.js";
import geolocationRouter from "./geolocation.js";
import tamvRouter from "./tamv.js";
import tamvThesisRouter from "./tamv-thesis.js";

const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/businesses", businessesRouter);
apiRouter.use("/donations", donationsRouter);
apiRouter.use("/weather", weatherRouter);
apiRouter.use("/recommendations", recommendationsRouter);
apiRouter.use("/ai", aiRouter);
apiRouter.use("/digital-twins", digitalTwinsRouter);
apiRouter.use("/content", contentRouter);
apiRouter.use("/realito", realitoRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/profiles", profilesRouter);
apiRouter.use("/social", socialRouter);
apiRouter.use("/streams", streamsRouter);
apiRouter.use("/protocols", protocolsRouter);
apiRouter.use("/economy", economyRouter);
apiRouter.use("/xr", xrRouter);
apiRouter.use("/audit", auditRouter);
apiRouter.use("/places", placesRouter);
apiRouter.use("/merchants", merchantsRouter);
apiRouter.use("/twins", twinsRouter);
apiRouter.use("/experience", experienceRouter);
apiRouter.use("/", systemRouter);
apiRouter.use("/rdmx", rdmxStatusRouter);
apiRouter.use("/geolocation", geolocationRouter);
apiRouter.use("/tamv", tamvRouter);
apiRouter.use("/tamv", tamvThesisRouter);

export default apiRouter;
